services:
  runtime-rust:
    image: crpi-yh02yjkhdi325jm5.cn-hangzhou.personal.cr.aliyuncs.com/pnos/runtime-rust:latest
    container_name: runtime-rust
    restart: unless-stopped
    working_dir: /data/project
    ports:
      - "2222:22"
    volumes:
      - ./data:/data
    environment:
      - SCCACHE_DIR=/data/sccache
      - SCCACHE_CACHE_SIZE=20G
    networks:
      - panda-net

networks:
  panda-net:
    external: true
