services:
  runtime-rust:
    image: crpi-yh02yjkhdi325jm5.cn-hangzhou.personal.cr.aliyuncs.com/pnos/runtime-rust:latest
    container_name: runtime-rust
    restart: unless-stopped
    working_dir: /workspace
    ports:
      - "2222:22"
    volumes:
      - ./project:/workspace
      - ./sccache-cache:/cache/sccache
      - ./cargo-registry:/usr/local/cargo/registry
      - ./authorized_keys:/root/.ssh/authorized_keys:ro
    environment:
      - SCCACHE_DIR=/cache/sccache
      - SCCACHE_CACHE_SIZE=20G
    networks:
      - panda-net

networks:
  panda-net:
    external: true
